### ISSUE TITLE
Position regulation - problem with PID constants

### ISSUE THREAD

**Issue by JarekParal** [ddemidov/ev3dev-lang-cpp#1]
I tried to set PID constants on position regulator by this command `set_position_p(int v)` and I got this error: 

> Unhandled exception: Operation not supported
> Terminating

I normaly use the position regulator by these commands

	motor.set_speed_regulation_enabled("on");
	motor.set_speed_sp(speed);
	motor.set_position_sp(position);
	motor.run_to_rel_pos();

and this is working, but I couldn't set the PID constants.

Do I something wrong or is it problem somewhere else?

Thanks you for any advice or help.

**Comment by ddemidov** [comment]
Hold (position) PID parameters are not implemented for the tacho motor drivers, see https://github.com/ev3dev/ev3dev-lang/issues/88. Are you looking for speed regulation PID parameters (`speed_regulation_p`, `_i`, `_d`)?

**Comment by ddemidov** [comment]
Also see https://github.com/ev3dev/ev3dev/issues/314
