### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by anonyme0** [ddemidov/ev3dev-lang-cpp#13]
I have installed this in my docker container. However, when I run arm-linux-gnueabi-g++ -o main main.cpp (in which there is #include <ev3dev.h>), it doesn't work. I'm really new to cross-compilation and linux, so consider this question as a beginner question.

**Comment by ddemidov** [comment]
`<>` brackets are used in C++ to reference system headers (installed in standard system locations). If you have `ev3dev.h` lying next to `main.cpp`, you should either change the include line to be
```cpp
#include "ev3dev.h"
```
or tell the compiler to look inside the current directoty:
```cpp
arm-linux-gnueabi-g++ -o main main.cpp -I.
```
Also, you need to pass the `ev3dev.cpp` to the compiler as well:
```cpp
arm-linux-gnueabi-g++ -o main main.cpp ev3dev.cpp -I.
```

**Comment by anonyme0** [comment]
Thanks a lot, I works fine now! Just one more question: what's the difference between:
   set_speed_sp()
   set_speed_p()
   set_speed_i()
   set_speed_d()
int the motor class? I your remote-control.cpp example, you use set_speed_sp(), why?
Thanks again for your answer

**Comment by ddemidov** [comment]
`speed_sp` is the speed (in degrees per second) you want the motor to turn with. `speed_{p,i,d}` are PID controller parameters that are used for speed regulation. You probably don't need those. See documentation on the API here: http://ev3dev-lang.readthedocs.io/en/latest/classes.html#Motor.Speed_SP

**Comment by anonyme0** [comment]
Thanks a lot!
