### ISSUE TITLE
Cross-compile on PC

### ISSUE THREAD

**Issue by anonyme0** [ddemidov/ev3dev-lang-cpp#14]
I'm trying to set up a friend's computer (a PC, while mine is a MAC) and I'm having an issue with the MentorGraphics toolchain: I can't compile with the -std=c++11 / -std=c++0x flag. Any ideas?

**Comment by ddemidov** [comment]
Do you get an error message from the compiler when you try to do this?

**Comment by anonyme0** [comment]
Yes.

**Comment by WasabiFan** [comment]
@anonyme0 I think Denis was asking for the actual text of the error message; he wants to know what command you ran and what it outputted.

**Comment by anonyme0** [comment]
Sadly I don't have the computer now :(
However, I do remember the command I ran:
arm-none-linux-gnueabi-g++ -o test -std=c++11 main.cpp ev3dev.cpp
I put ev3dev.cpp and ev3dev.h in the same folder as main.cpp. I have also tried  with -std=c++0x, -std=gnu++11 and -std=gnu++0x.
It either displays "command line option not found" or an endless list of errors.

**Comment by ddemidov** [comment]
When you have the computer, can you please post the exact command line you used, and the error message you got? I don't have a windows computer, so I can not check this on my own.

**Comment by WasabiFan** [comment]
FYI, you can download Windows Insider builds for free (presumably to run in a VM) for testing things in the future. Aside from the fact that you're forced to update it occasionally, it's pretty much just a free copy of standard Windows.

**Comment by ddemidov** [comment]
To be honest, I do have a Windows installed as a secondary OS, but every time I boot into it, it wants  to do things with my PC, which usually take up to an hour of 'do not turn your computer off, I am working', followed by 'I tried, but failed, lets reboot and try again'. By the time its done, I usually already have forgot why I booted into it :smile:

**Comment by anonyme0** [comment]
In few days (2-3) I will have access to this computer. However I already have a (prehistoric) PC somewhere in my closet and I think I will try to to install the MentorGraphic Toolchain on it (it will probably take me more than hour).

**Comment by anonyme0** [comment]
OK. I just installed the MentorGraphic Toolchain on my PC and… it works! I definitely made an error somewhere on my friend's computer. Guess I will have to do it all over again now. Anyway thanks for your time and sorry for not having tried earlier.
