### ISSUE TITLE
Problem while compiling

### ISSUE THREAD

**Issue by EduPonz** [ddemidov/ev3dev-lang-cpp#15]
I am having a proving while compiling, aparently the compiler cannot find the ev3dev.h file eventhoug I have clone this repository as you can see. What am I doing wrong?
```
eduponz@ubuntu:~/forklift_ws$ ls
ev3dev-lang-cpp  forklift.cpp
eduponz@ubuntu:~/forklift_ws$ g++ -std=c++11 forklift.cpp -o forklift
forklift.cpp:8:20: fatal error: ev3dev.h: No such file or directory
compilation terminated.
eduponz@ubuntu:~/forklift_ws$ 
```

**Comment by WasabiFan** [comment]
@ddemidov will be be one that can help, but I suspect he'll want to see the `#include` directives you're using. Can you share those lines as well as any other relevant bits?

**Comment by ddemidov** [comment]
You need to tell the compiler where to find the header. Also, you need to compile and link your program with ev3dev.cpp. So the command line should look like this:
```
g++ -o forklift forklift.cpp ev3dev-lang-cpp/ev3dev.cpp -std=c++11 -I./ev3dev-lang-cpp
```

**Comment by EduPonz** [comment]
And it worked!! Thank you so much!! It is my first time compiling through terminal and I had no idea about how to proceed

**Comment by ddemidov** [comment]
You will need to use a cross-compiler if you want to actually run the compiled program on the EV3. See http://www.ev3dev.org/docs/tutorials/using-docker-to-cross-compile/.

For simple examples it should also be possible to use `g++-arm-linux-gnueabi` ubuntu package (and replace `g++` with `arm-linux-gnueabi-g++` in your command).
