### ISSUE TITLE
version `GLIBCXX_3.4.21' not found

### ISSUE THREAD

**Issue by Martineee** [ddemidov/ev3dev-lang-cpp#17]
Hey,

I currently have a problem regarding how to make my C++ programs run on the EV3 dev (lego mindstorm).

When I try to run my program (called driveTest), I get the following error message:

 **./driveTest: /usr/lib/arm-linux-gnueabi/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./driveTest)**

I found a simular issue on askubuntu.com ([,](http://askubuntu.com/questions/575505/glibcxx-3-4-20-not-found-how-to-fix-this-error)) and tried to do as the comments recommended:

**sudo apt-get install libstdc++6** (which was already installed)
**sudo add-apt-repository ppa:ubuntu-toolchain-r/test** (some errors)
**sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade**

But unfortunately, it did not solve my problem.
I do not know what to do next. Could you please help me?

**Comment by ddemidov** [comment]
This looks like a compatibility issue between the compiler you used and the ev3dev. Namely, it looks like your cross-compiler has version of libstdc++ that is different from the one ev3dev has.

**Comment by Martineee** [comment]
Thank you for your help. I have now copied the version of libstdc++ from my cross compiler to the ev3dev, and it seems to work, even though it is not standard...

**Comment by ddemidov** [comment]
You could try to link libstdc++ statically: http://stackoverflow.com/a/26107550/996848
