### ISSUE TITLE
Linking error with libev3dev.a

### ISSUE THREAD

**Issue by agentS** [ddemidov/ev3dev-lang-cpp#18]
Hi,

First of all thank you for this great libary. I am really looking forward to give it a try.

I have set up the official ev3dev docker container for cross compilation and I have been able to cross compile simple C/C++ programs as well as your library.

However, there seems to be something wrong with the cross compilation of your library. Inspite of being able to include the header file as well as pass it to the linker, there are linking errors when calling methods of the `motor` class. I get the following error:

    libev3dev.a: error adding symbols: File format not recognized

This indicates that the library has not been compiled for the same architecture as my program. I have followed the instructions in your README file to compile the static library. I am using the `arm-linux-gnueabi-g++` compiler in order to compile my program. Furthermore, I have set the following environment variables in order to make sure that CMake uses the correct compiler

    ev3dev@spt:~/development/brickCollector$ echo $CC
    arm-linux-gnueabi-gcc
    ev3dev@spt:~/development/brickCollector$ echo $CXX
    arm-linux-gnueabi-g++

My Makefile can be seen below:

    PROGNAME=brickCollector
    CC = arm-linux-gnueabi-g++
    #CC = g++
    CFLAGS = -g -Wall -std=c++11 -c -I /home/ev3dev/development/ev3dev-lang-cpp
    LDFLAGS = -Wall -o
    LIBS = -L/home/ev3dev/development/ev3dev-lang-cpp/build -lev3dev

    all: $(PROGNAME)

    ${PROGNAME}: brickCollector.o
        $(CC) $(LDFLAGS) $(PROGNAME) brickCollector.o $(LIBS)

    brickCollector.o: brickCollector.cpp brickCollector.h
        $(CC) $(CFLAGS) brickCollector.cpp

    install:
        cp $(PROGNAME) /home/ev3dev/development/ev3/$(PROGNAME)

    clean:
        rm -f $(PROGNAME) *.o *.out

The function causing the issue is shown below.

    void motor_action(motor &dev)
    {
        cout << "Address: " << dev.address() << endl;
    }

I would be most graceful if you could tell me the compiler being used for compiling your library.

Yours sincerely,

Lukas

**Comment by ddemidov** [comment]
What are you using as a linker (echo $LD)?

**Comment by agentS** [comment]
I am letting `arm-linux-gnueabi-g++` select the linker. I have updated the issue and included my makefile.

**Comment by ddemidov** [comment]
I can not test this right now, but in the meanwhile the following might work:
```
${PROGNAME}: brickCollector.cpp brickCollector.h ev3dev.cpp ev3dev.h
        $(CC) $(LDFLAGS) $(CFLAGS) brickCollector.cpp ev3dev.cpp
```

**Comment by ddemidov** [comment]
> I would be most graceful if you could tell me the compiler being used for compiling your library.

I have tested the library with [Sourcery codebench](https://www.mentor.com/embedded-software/sourcery-tools/sourcery-codebench/overview) crosscompiler (available as `sourcery-codebench-arm-none-linux-gnueabi` package in Arch linux), and also I think the [Using Docker to Cross-Compile](http://www.ev3dev.org/docs/tutorials/using-docker-to-cross-compile/) worked for me as well.

**Comment by agentS** [comment]
I fixed it by adding the following two lines to the CMakeLists.txt file:

    set (CMAKE_C_COMPILER arm-linux-gnueabi-gcc)
    set (CMAKE_CXX_COMPILER arm-linux-gnueabi-g++)

I know it's not the optimal solution, but it works.

**Comment by ddemidov** [comment]
Ah, so you were building the library with cmake (with normal compiler), and then linking it with cross-compiler. That makes sense now.

> I fixed it by adding the following two lines to the CMakeLists.txt file:

You can achieve the same result with the following:
```
cd ev3dev-lang-cpp/build
rm -rf *
CC=arm-linux-gnueabi-gcc CXX=arm-linux-gnueabi-g++ cmake ..
make
```
cmake will pick the environment variables and cache those.
