### ISSUE TITLE
Configuring / Accessing sensors on PiStorms query.

### ISSUE THREAD

**Issue by floydbloke** [ddemidov/ev3dev-lang-cpp#22]
Beginner's query here.  I am running EV3DEV on a PiStorms V2
I have made some edits to ev3dev.h to map PiStorms ports like so
`#ifdef EV3DEV_PLATFORM_PISTORMS`
`constexpr char INPUT_1[] = "pistorms:BA:S1";  //!< Sensor port 1`
`constexpr char INPUT_2[] = "pistorms:BA:S2";  //!< Sensor port 2`
`constexpr char INPUT_3[] = "pistorms:BB:S1";  //!< Sensor port 3`
`constexpr char INPUT_4[] = "pistorms:BB:S2";  //!< Sensor port 4`

`constexpr char OUTPUT_A[] = "pistorms:BAM1"; //!< Motor port A`
`constexpr char OUTPUT_B[] = "pistorms:BAM2"; //!< Motor port B`
`constexpr char OUTPUT_C[] = "pistorms:BBM1"; //!< Motor port C`
`constexpr char OUTPUT_D[] = "pistorms:BBM2"; //!< Motor port D`
`#else`
`...`

With a motor attached to BAM1, the code below compiles (on the Pi for now) and executes fine.  It displays the hello string in the console  and runs the motor for a short while (5 seconds I assume).

`int main()`
`{`
   ` cout << "Hello from pistorms!\n";`
  `      motor mymotor(OUTPUT_A); `
 `       mymotor.set_speed_sp(900); `
`        mymotor.set_time_sp(5000).run_timed();`
`    return 0; `
`}`

I'm now trying to connect and access some sensors.  I understand that the PiStorms unit is not auto-sensing and I need to manually set the mode and possibly the sensor device that is attached.  I can't figure out how to do this programmatically.  I have attempted things like
`lego_port myport(INPUT_1);`
or
`touch_sensor mytouch(INPUT_1);`

but they invariably return 
`terminate called after throwing an instance of 'std::system_error'`
`  what():  no device connected: Function not implemented`
when trying to retrieve value or mode.

(reading the sensor works OK via the console through the lego-port 'class'.)

Looking for some guidance please on how to configure and access the sensor ports on my PiStorms.

**Comment by ddemidov** [comment]
> reading the sensor works OK via the console through the lego-port 'class'.

Can you provide here what exactly you did in the console? Also, can you paste the output of the `cat /sys/class/lego-port/port*/address` here? I am sorry, I don't own a PiStorms, so I can not test this myself.

**Comment by floydbloke** [comment]
` cat /sys/class/lego-port/port*/address` 
outputs
`pistorms:BBS1`
`pistorms:BBS2`
`pistorms:BBM1`
`pistorms:BBM2`
`pistorms:BAS1`
`pistorms:BAS2`
`pistorms:BAM1`
`pistorms:BAM2`

Seeing this prompted me to change the ev3dev.h
from
`constexpr char INPUT_1[] = "pistorms:BA:S1";  //!< Sensor port 1` to
`constexpr char INPUT_1[] = "pistorms:BAS1";  //!< Sensor port 1`
and it now works as expected, I can successfully read the touch sensor.
( I used the input port syntax  from here initially: [http://docs.ev3dev.org/projects/lego-linux-drivers/en/ev3dev-jessie/pistorms.html#pistorms-in-port-notes](url) )

To answer the first part of the question, my console commands were
`cd /sys/class/lego-port/port4`  (port no. obtained from Brickman
`echo ev3-analog > mode`
`cd /sys/class/lego-sensor/sensor0`
`cat value0`

Thank you for your help.
