### ISSUE TITLE
Problems with executing on brick

### ISSUE THREAD

**Issue by Gavaz10** [ddemidov/ev3dev-lang-cpp#28]
I compiled demos on bash windows 10, then i tried to execute it on the EV3(ev3dev) brick, but when i am trying to start some program it says : " /usr/lib/arm-linux-gnueabi/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./button-test) ". I tried to download newest version of gcc, but it's no version higher than gcc-4.9. What to do? I am new on linux.

**Comment by ddemidov** [comment]
Looks like duplicate of #17. Also, it seems the best current way to cross-compile is with docker, see http://www.ev3dev.org/docs/tutorials/using-docker-to-cross-compile/, #27.

**Comment by Gavaz10** [comment]
Thank you very much. It finally works.(with docker)
