### ISSUE TITLE
Making it work with ROS

### ISSUE THREAD

**Issue by MadsFox** [ddemidov/ev3dev-lang-cpp#29]
Desperate for a tutorial a guide or help to make a ROS node running on a EV3 brick. I have with success run a Python node with the talker listener tutorial. And a Python node that prints numbers from a sensor, but can't combine them because one is on Python2 and the other on Python3. Therefore I now try to get a C++ node up and running, but I don't know how to install and setup this library and how to get a working environment. 
How do I install it on the EV3 and how do I use it in a project? I work on a Linux Ubuntu machine, so that should make it easier. 
I have figured out how to mount the EV3 file system on my Linux computer and have worked with docker. Now I just need to build a ROS node to run on the EV3 using this library to access the EV3's sensors and motors. Just wanna be sure how to include this library.

**Comment by ddemidov** [comment]
I have no experience with ROS (actually have no idea what that is), but if you tell me what exactly you are trying to do with this library, I could try to help you.

To use the library you can just copy `ev3dev.cpp` and `ev3dev.h` files into your project and compile it however you do compilation (see the README for some more info). Something like `CXX -std=c++11 -O3 -o myproject ev3dev.cpp myproject.cpp`, where `CXX` is your compiler command. 

If you want to use the library in stretch, you'll need to make a couple of changes, similar to https://github.com/rhempel/ev3dev-lang-python/commit/06ae05faf27fc5d33dc5d26742a11ed2bc82e937. Namely, you'll need to change these parts of the code:

https://github.com/ddemidov/ev3dev-lang-cpp/blob/539f24107019f3b1c802444b1c2970516b0c043f/ev3dev.cpp#L954-L957

https://github.com/ddemidov/ev3dev-lang-cpp/blob/539f24107019f3b1c802444b1c2970516b0c043f/ev3dev.cpp#L1022

**Comment by moriarty** [comment]
Hi,

Sorry this post might not be helpful. I’m currently away for work with limited internet access... but I just wanted to link this to another issue:

https://github.com/moriarty/ev3dev_ros_demo/issues/1#issuecomment-335918993

**Comment by MadsFox** [comment]
@ddemidov: for some reason I still can't connect to any of the sensors, motors, leds, but the sound part of the test menu works fine and also the lcd part, but it looks like they are not dependent on connecting. What can be the problem?

**Comment by ddemidov** [comment]
Are you using stretch?

**Comment by MadsFox** [comment]
Yes and I have placed the ev3dev.cpp and ev3dev.h file in the src folder of my project and added it in my CMakelists file: 
`add_library(ev3dev src/ev3dev.cpp)` My CMakelists file is in the project folder and the ev3dev files in the src folder.
I have also specified the library as a target link library:
`target_link_libraries(ev3dev_test_node
   ${catkin_LIBRARIES}
   ev3dev
 )
target_link_libraries(ev3dev
   ${catkin_LIBRARIES}
 )
`
I have tried to put some `cout` calls in the ev3dev.cpp file, but they didn't get printed in the terminal.

**Comment by MadsFox** [comment]
I have also checked that the SYS_ROOT matches the root of the classes on the EV3. Also I can see the sensors and motors and their values via the LCD screen.
Sorry i'm new to C++, so my questions might be flawed them self.

**Comment by ddemidov** [comment]
I'll try to compile the tests when I have time (probably this weekend).

**Comment by ddemidov** [comment]
Meanwhile, could you please check if #30 helps you? It affects leds, buttons, and port names. Note that if you use strings to specify addresses, as in
```cpp
ev3dev::large_motor m("outA");
```
then you should change that to
```cpp
ev3dev::large_motor m("ev3-ports:outA");
```
or, better yet, use the provided constants:
```cpp
ev3dev::large_motor m(ev3dev::OUTPUT_A);
```

**Comment by MadsFox** [comment]
thank you so much @ddemidov made the test node run the motor and it registered the sensors, thank you, thank you, thank you.
It was a matter of changing the port names.
Still an issue with the leds, but I don't need to work in my project.
