### ISSUE TITLE
Changing Font Size of Console Output

### ISSUE THREAD

**Issue by Cyperfr3ak** [ddemidov/ev3dev-lang-cpp#35]
Is there a way to change the font size of the console? When I print something with cout it is very hard to read on the Display of the EV3.

**Comment by ddemidov** [comment]
I think what you get on ev3dev is a normal linux console, which uses hard coded fonts when you send something to stdout. You could probably try something like [this](https://wiki.archlinux.org/index.php/Fonts#Console_fonts) to change those. Or you could use some other library to draw directly to the framebuffer.

**Comment by WasabiFan** [comment]
I believe you can do this by executing the `setfont` program. There's a Python example here: https://github.com/ev3dev/vscode-hello-python/blob/master/hello.py#L39

**Comment by Cyperfr3ak** [comment]
Thanks got it working by just changing standard font for console.
