### ISSUE TITLE
EV3 Motors not detected

### ISSUE THREAD

**Issue by timmmerlan** [ddemidov/ev3dev-lang-cpp#36]
Hi all,
I have problems with the EV3 motors - neither in the drive-test program nor in other programs they are  detected with the .connected() command.
On the EV3, I am running brickman v0.8.1 with the 4.4.87-22-ev3dev-ev3 Kernel.
Thank you for your help!

**Comment by ddemidov** [comment]
Can you try to use the code from the [`jessie`](https://github.com/ddemidov/ev3dev-lang-cpp/tree/jessie) branch? The master is synced with the `stretch` kernel, while you seem to run the `jessie` one.

**Comment by timmmerlan** [comment]
Worked perfectly, thank you!
