### ISSUE TITLE
cannot connect to lego motors on ev3

### ISSUE THREAD

**Issue by mo82abbasi** [ddemidov/ev3dev-lang-cpp#39]
I have cross compiled demo programs in demos directory on my Windows 10 machine and transferred the binary files to my ev3. Some of them work fine but not all of them.
For example button-test and sound-test work on my ev3. 
But some of the demo programs don't work. For example it seems that it cannot connect to motors in demos/drive-test program. It fails in the very beginning when it checks for initialization below:  
int main()
{
control c;
if( c.initialized() )

I have two lego motors connected to output B and C on my ev3. 
I can see this : 
/sys/class/tacho-motor/motor0
/sys/class/tacho-motor/motor1

and if I try something like the following commands, they all work! 
echo reset > /sys/class/tacho-motor/motor0/command 
echo run-forever > /sys/class/tacho-motor/motor0/command

Does anyone know what can be the problem? or where should I start to find the problem?

**Comment by ddemidov** [comment]
Looks like you are using master branch with the stable (jessie) image of ev3dev. If that is the case, please try using the `jessie` branch [here](https://github.com/ddemidov/ev3dev-lang-cpp/tree/jessie) instead.

**Comment by mo82abbasi** [comment]
that was exactly the problem. 
case solved. 
Thanks for your quick help.
