### ISSUE TITLE
How to build my first test program?

### ISSUE THREAD

**Issue by Tom-Shen** [ddemidov/ev3dev-lang-cpp#4]
I am new to this, and I have setup Brickstrap environment, it works fine, I would like to use your button-test.CPP program, I have copied it to my Brickstrap environment, what is the next step?

**Comment by ddemidov** [comment]
In order to compile the `button-test.cpp` example, you will also need `ev3dev.cpp` and

**Comment by ddemidov** [comment]
In order to compile the example, you will also need `ev3dev.cpp` and `ev3dev.h` files. You can call g++ directly:
```
g++ -o button-test -std=c++11 button-test.cpp ev3dev.cpp
```
This will produce the `button-test` executable, which you can copy to the ev3.

**Comment by Tom-Shen** [comment]
Thank you for your kindly help, I will try it.
