### ISSUE TITLE
BrickPI 3 doesn't find motors on Jessie

### ISSUE THREAD

**Issue by stefmorren** [ddemidov/ev3dev-lang-cpp#40]
Hello

I'm using the Jessie branch because i'm using the EV3DEV Jessie. My system runs on a Raspberry Pi3 with a BrickPi 3. I can succesfully build the demos but I can't connect with my motors in any script.

I did some research and I found that in de EV3DEV.h file the addresses for the Brickpi are wrong. They are still using the old addresses.  (see http://www.ev3dev.org/docs/platform-comparison/) 

Then I tried changing them to "spi0.1:Mx" but I still can't connect to them after a rebuild.

**Comment by ddemidov** [comment]
Can you look for the actual addresses using bash and the sysfs file system (see http://www.ev3dev.org/docs/tutorials/tacho-motors/)? For example, something like
```
cat /sys/class/tacho-motor/motor0/address
```
should give you the address of the motor0. What value do you see there?

**Comment by stefmorren** [comment]
This returns spi0.1:MA but if I use them in the ev3dev.h they still don't recognize the motors.

**Comment by ddemidov** [comment]
When you say you are using the addresses in ev3dev.h, you mean you update them [here](https://github.com/ddemidov/ev3dev-lang-cpp/blob/master/ev3dev.h#L63-L71), right? Do you also use preprocessor definition `EV3DEV_PLATFORM_BRICKPI`?

**Comment by stefmorren** [comment]
I'm using this for compiling the scripts
`mkdir build
cd build
cmake .. -DEV3DEV_PLATFORM=BRICKPI
make`

The demo's doesn't work anymore with the BrickPI3. For example, I get errors because it doesn't find the green and the red light. (BrickPi3 only has one 1 yellow light) 

I changed the demo and removed everything from the led lights so that I can compile. I added an cout just before the motor connection and it prints the correct address (spi0.1:MB)

I changed the addresses in the ev3dev.h (Only from the motors)
`#if defined(EV3DEV_PLATFORM_BRICKPI)
constexpr char INPUT_1[]  = "ttyAMA0:in1";  //!< Sensor port 1
constexpr char INPUT_2[]  = "ttyAMA0:in2";  //!< Sensor port 2
constexpr char INPUT_3[]  = "ttyAMA0:in3";  //!< Sensor port 3
constexpr char INPUT_4[]  = "ttyAMA0:in4";  //!< Sensor port 4

constexpr char OUTPUT_A[] = "spi0.1:MA"; //!< Motor port A
constexpr char OUTPUT_B[] = "spi0.1:MB"; //!< Motor port B
constexpr char OUTPUT_C[] = "spi0.1:MC"; //!< Motor port C
constexpr char OUTPUT_D[] = "spi0.1:MD"; //!< Motor port D
`
With the remote-control script it keeps giving me 

> terminate called after throwing an instance of 'std::runtime_error'
  what():  Motor on outB is not connected

Am I doing something wrong or is this library not compatible with BrickPI3?

**Comment by ddemidov** [comment]
Unfortunately, I don't have a brickpi to test this. May be @dlech will be able to spot something right away. Otherwise, may be you could try to go step-by-step over the code in a debugger and see what exactly goes wrong?

**Comment by stefmorren** [comment]
When I'm debugging in gdb the remote-control application immediately crashes on the precondition(lmotor.connected(), "Motor on outB is not connected");

I haven't used C++ in a long time and I have never used it in a Linux environment, so this stuff is pretty new to me.  I'm building a robot for in an automated warehouse system which uses SLAM and object recgonition with an EV3 with an 3D camera. This system will be running under ROS, ROS also supports Python but only Python2.7, and I can't seem to get ROS working with Python3+, that's why I moved to C++ because both systems support C++. I'm doing this as my internship so I really need to get this working :/ Can you point me in a few other directions which or what I should debug?

**Comment by dlech** [comment]
BrickPi and BrickPi3 are totally different boards, so should have a different compile option.

"spi0.1:MA" looks correct for motor ports, but the sensor ports should looks something like ""spi0.1:S1"

See http://www.ev3dev.org/docs/platform-comparison/

**Comment by dlech** [comment]
> what(): Motor on outB is not connected

Since this says "outB" it looks like it is not picking up your changes, unless the name "outB" is hard coded in the error message somehow.

**Comment by ddemidov** [comment]
The message (but not the address) is hardcoded here: https://github.com/ddemidov/ev3dev-lang-cpp/blob/master/demos/remote-control.cpp#L66

**Comment by dlech** [comment]
OK, so "outB" is hard-coded in the error message.

**Comment by stefmorren** [comment]
Yes "outB" is hard-coded in the error message, but I checked right before the motor connection is made if the address is spi0.1:Mx.

**Comment by ddemidov** [comment]
I would try to replace 'large_motor' with just 'motor' in the demo code,
and see if that helps. Also, you may try to omit the address from the motor
constructor (it should connect any available motor then), but I guess it
would not make a difference, since you've checked the address is correct.


-- 

Cheers,
Denis

**Comment by dlech** [comment]
> I would try to replace 'large_motor' with just 'motor' in the demo code,

Ah, yes. On BrickPi3 it will identify the motors as NXT motors instead of EV3 Large motors.

**Comment by stefmorren** [comment]
Okay I'm going to try it now, I did noticed indeed that the motors are detected as NXT motors.

**Comment by stefmorren** [comment]
@dlech @ddemidov the large_motor changing to just motor fixed it guys! 👍 Thanks for your support! Maybe you should add this to the readme. :) 

Your help was much appreciated!

**Comment by ddemidov** [comment]
be3fe95 and 71fa951 add correct port names for the BrickPi3 platform.

**Comment by ddemidov** [comment]
And the amber led should be covered by 2da4782 and b1189b8. @stefmorren, it would be great if you could test that these actually work. Thanks!

**Comment by stefmorren** [comment]
@ddemidov I will do this tomorrow!

**Comment by ddemidov** [comment]
So should the addresses be `spi0.1:MA` - `spi0.1:MD`?

**Comment by ddemidov** [comment]
See 208e1b1, a420c2a and thanks!

**Comment by stefmorren** [comment]
Happy to help! :) The addresses are correct now! :)

**Comment by stefmorren** [comment]
@ddemidov i've tested the amber light and it works fine! :)

**Comment by ddemidov** [comment]
Thanks for testing, @stefmorren! I'll close this then.
