### ISSUE TITLE
connect multiple motors to one EV3 port

### ISSUE THREAD

**Issue by timmmerlan** [ddemidov/ev3dev-lang-cpp#41]
Hello,
I would like to attach multiple medium EV3 motors to one port of the EV3. That is possible with the cables delivered with the NXT that were actually for using the lamps. Is there any way I can use the motor (of course not the rotation sensors, but just giving power on them for a certain time) with C++?
I tried declaring it as dc_motor, but always get the error that no device is connected.
Thank you for your help!

**Comment by timmmerlan** [comment]
It is not actually a multiplexer. But just a cable that converts from the port of the EV3 to a lego brick connection that transmits electricity and back. So I don't believe it is possible to get any data from the motor. I just know from the standard Mindstorms software that you can put power on the port and both motors turn.

**Comment by dlech** [comment]
I suppose you could do that. You should set the port to `dc-motor` mode and use the `dc_motor` class.

**Comment by timmmerlan** [comment]
Thank you for the suggestions! I tried using
`motor motorname (OUT_C, {"dc_motor"});`
but still got a system error at the start of the program. Maybe I am missing something? For the moment, I found another solution going around this (in terms of construction of the robot), so it is not that urgent any more, but I will try to play with this later when I have time.

**Comment by dlech** [comment]
I was going to suggest to suggest that you should use the `lego_port` class, but it doesn't look like it has any useful methods. As a workaround, you can use the Brickman user interface to manually change the mode of the port before you start your program.

**Comment by dlech** [comment]
Those are the methods I was looking for. For some reason I couldn't find them.

**Comment by timmmerlan** [comment]
Thank you for the suggestions! I tried using
`motor motorname (OUT_C, {"dc_motor"});`
but still got a system error at the start of the program. Maybe I am missing something? For the moment, I found another solution going around this (in terms of construction of the robot), so it is not that urgent any more, but I will try to play with this later when I have time.
