### ISSUE TITLE
Cross Compiling on Windows command not working

### ISSUE THREAD

**Issue by cgu2022** [ddemidov/ev3dev-lang-cpp#46]
Hi guys, I followed all the steps on the cross-compiling tutorial for the linux subsystem, except instead of installing gcc5/unstable I installed gcc6/stable on the ev3. Anyhow, on the subsystem, I tried running:

"arm-linux-gnueabi-g++ test.c -lev3dev-c -o test",

and it said it couldn't recognize the "ev3.h" file I included like this:

test.c:1:10: fatal error: ev3.h: No such file or directory
 #include "ev3.h"
          ^~~~~~~

Is there anything I'm missing here?
Thanks!

**Comment by ddemidov** [comment]
Did you mean to `#include` ["ev3dev.h"](https://github.com/ddemidov/ev3dev-lang-cpp/blob/master/ev3dev.h)? Also, you may need to add `-I /path/to/ev3.h` to the compiler options.

**Comment by cgu2022** [comment]
Okay I looked at the demos and that makes sense. Do you know where I could find the documentation of the functions and each class? I tried looking for it and they were vague and did not have the functions.

**Comment by ddemidov** [comment]
Unfortunately, the best documentation for the C++ bindings we currently have is the header file:
https://github.com/ddemidov/ev3dev-lang-cpp/blob/master/ev3dev.h
and [demos](https://github.com/ddemidov/ev3dev-lang-cpp/tree/master/demos).

The API should be close to the [python one](https://python-ev3dev.readthedocs.io/en/ev3dev-stretch/?badge=ev3dev-stretch) which is better documented, so you could also peek there.

**Comment by cgu2022** [comment]
Okay, thank you!

**Comment by cgu2022** [comment]
Hey again, I tried ran the "ev3dev-lang-test" executable on the ev3, but it couldn't detect the motors. I saw that people who were running the jessie ev3dev had the issue of not using the jessie branch. So, I compared the jessie branch with the master branch to verify that I was using the jessie branch, but it still didn't work.

Is there something I'm missing? And also, is there a github command I can run on the subsystem that verifies I am using the jessie branch?

**Comment by ddemidov** [comment]
> is there a github command I can run on the subsystem that verifies I am using the jessie branch?

`git brach` should show you the current branch, and `git log` show show you sha1 hash of the last commit. On the jessie branch it should be 208e1b13a2a0b17402a6180f984d3f0e843c934f.

Also, check your motor addresses in  `/sys/class/motors/motor*/address`, and see if they are the same as

https://github.com/ddemidov/ev3dev-lang-cpp/blob/208e1b13a2a0b17402a6180f984d3f0e843c934f/ev3dev.h#L98-L101

**Comment by cgu2022** [comment]
Okay I found that I guess I was still using the master branch, so I changed it to jessie with `git checkout jessie`. And now it works. Thanks!
