### ISSUE TITLE
CMakeLists.txt forces C++11, breaking C++14 projects wanting to include it

### ISSUE THREAD

**Issue by alexdewar** [ddemidov/ev3dev-lang-cpp#51]
Currently we have this line in CMakeLists.txt:
```
target_compile_options(ev3dev PUBLIC -std=c++0x)
```
The problem is that by making this option public, any project which includes it (with ``add_subdirectory()``) will also be set to use C++11, which will break things if the user also wants to use C++14 code.

Changing the ``PUBLIC`` to ``PRIVATE`` fixes things for me. Another option would be to use the newer ``${CMAKE_CXX_STANDARD}`` variable if the user's version of cmake supports it: https://stackoverflow.com/questions/10851247/how-to-activate-c-11-in-cmake

**Comment by ddemidov** [comment]
> Another option would be to use the newer ${CMAKE_CXX_STANDARD} variable

I think this should work. Would you like to provide a pull request?

**Comment by alexdewar** [comment]
Sure, I'll have a go.
