### ISSUE TITLE
Mindstorms freezes while doing apt-get update

### ISSUE THREAD

**Issue by Niels1006** [ddemidov/ev3dev-lang-cpp#58]
Hey, 

I have the latest ev3dev installed on my mindstorms.

After I added these: `deb http://httpredir.debian.org/debian unstable main contrib non-free
deb http://security.debian.org/ unstable/updates main contrib non-free
deb http://archive.ev3dev.org/debian unstable main` (tutorial)

my mindstorms freezes at around 95-99% when I do `sudo apt-get update` or `sudo apt-get install gcc-5/unstable`.

Thank you for helping.

**Comment by ddemidov** [comment]
You should ask this at https://github.com/ev3dev/ev3dev/issues

**Comment by Niels1006** [comment]
Okay, imma do that.
Thank you :)
