### ISSUE TITLE
Dual licensing

### ISSUE THREAD

**Issue by ddemidov** [ddemidov/ev3dev-lang-cpp#7]
It was requested in a private email to switch from GPL to LGPL or a dual licensing scheme. I don't mind in principle (although  I would prefer MIT/BSD type license), but the repo has a lot of contributions by other developers, namely @fdetro and @WasabiFan.

This issue is to discuss the proposed license change.

**Comment by WasabiFan** [comment]
I'm fine with changing the license (whether it's LGPL or dual). Honestly, I think that the LGPL is more useful in practice anyway; I'm fine if my code is used in private software, just as I am fine with it being used publicly.

Feel free to change it as you see fit!

---
P.S. Sorry I haven't responded to that thread; I'll read through the more recent emails and respond as appropriate later today.

**Comment by VincentLorenzo** [comment]
Hello everybody; 
   Thank you Denis to open the issue for me. I don't yet get an, answer from Eclipse on the forum, but I found the answer myself. GPL and LGPL are not possible in Eclipse. 

We would like to know if you will accept to change your license for the Eclipse Public Licence (it will be the easiest way for us) ?
Nevertheless, others licenses could be used, according to the 2nd page (right green comment) of this document : https://eclipse.org/legal/EclipseLegalProcessPoster.pdf 
these licences are possible in Eclipse for binaries code : 
For an unmodified binary distribution, the 
following licenses are considered approved as 
of the date of this Poster’s release:  
•Apache Software License 1.1  
•Apache Software License 2.0 
•W3C Software License 
•Common Public License Version 1.0 
•IBM Public License 1.0 
•Mozilla Public License Version 1.1
•Common Development and Distribution 
License (CDDL) Version 1.0
•GNU Free Documentation License Version 1.3
•BSD
•MIT

Licenses that are not approved as of the date 
of this Poster’s release include:
•GNU GPL 2.0
•GNU LGPL
•Sun Binary Code License Agreemen

Best regards, 
--
Vincent Lorenzo

**Comment by ddemidov** [comment]
How about MIT license then?

**Comment by fdetro** [comment]
I am ok with switching to MIT license, too.

**Comment by ddemidov** [comment]
@VincentLorenzo, would MIT license work for you?

**Comment by VincentLorenzo** [comment]
@ddemidov , Yes it is OK for us, Thank you very much
