### ISSUE TITLE
Motors not running in drive-test.cpp

### ISSUE THREAD

**Issue by ccimrie** [ddemidov/ev3dev-lang-cpp#9]
I've installed this library along with the ROS ev3dev setup (https://github.com/moriarty/ros-ev3/blob/master/brickstrap-build-status.md), and so far the sensors are working, however when I tried running the drive-test.cpp file the motors are not running. 

They're being acknowledged and showing that they are connected, but are not responding to the commands. Not sure if I've done something silly or not.

**Comment by ddemidov** [comment]
What kernel do you use? Some time ago there was a change in the motor drivers, so the version of the kernel and the version of the library should be compatible. The [remote-control](https://github.com/ddemidov/ev3dev-lang-cpp/blob/master/demos/remote-control.cpp) demo works for me on the [latest kernel](http://www.ev3dev.org/news/2016/06/14/Kernel-Release-Cycle-12/). Can you try that? The demo uses the explorer robot by Laurens Valk: http://robotsquare.com/2015/10/06/explor3r-building-instructions/.

**Comment by ddemidov** [comment]
Also, I've just noticed that `drive-test.cpp` uses `duty_cycle_sp` attribute to control the motors. This should be replaced by `speed_sp`, since in the latest kernels this is the only way to control motors. `duty_cycle_sp` is reserved for use with `run-direct` command.

**Comment by ddemidov** [comment]
The issue with `drive-test.cpp` should be fixed by 7b1cf10.

**Comment by ddemidov** [comment]
And a7ab4d6 updates `remote-control.cpp`. The changes were lying on my development machine, and I've just noticed I did not push those upstream. The `remote-control.cpp` should really work now :).

**Comment by ccimrie** [comment]
Yes, the change to speed_sp works, thank you!
